In [4]:
import math
import numpy as np

def cholesky_equicorrelation(n, rho):
    # Initialize a zero matrix
    L = [[0.0] * n for _ in range(n)]
    
    for i in range(n):
        for j in range(i + 1):
            # Calculate the sum of squares of previous elements in the row
            sum_sq = sum(L[i][k] * L[j][k] for k in range(j))
            
            if i == j:
                # Diagonal elements: sqrt(A[i][i] - sum_sq)
                # For correlation matrix, A[i][i] is always 1
                L[i][j] = math.sqrt(1.0 - sum_sq)
            else:
                # Off-diagonal elements: (A[i][j] - sum_sq) / L[j][j]
                # For equicorrelation, A[i][j] is always rho
                L[i][j] = (rho - sum_sq) / L[j][j]
    return L

# Test with n=4, rho=0.5
n = 4
rho = 0.5
L = np.array(cholesky_equicorrelation(n, rho))

print(f"Cholesky Factor L (rho={rho}):")
print(L)
print()
print(np.matmul(L, L.T))

Cholesky Factor L (rho=0.5):
[[1.         0.         0.         0.        ]
 [0.5        0.8660254  0.         0.        ]
 [0.5        0.28867513 0.81649658 0.        ]
 [0.5        0.28867513 0.20412415 0.79056942]]

[[1.  0.5 0.5 0.5]
 [0.5 1.  0.5 0.5]
 [0.5 0.5 1.  0.5]
 [0.5 0.5 0.5 1. ]]


In [5]:
from numpy.linalg import cholesky

rho = .4

corr = [[rho] * n for _ in range(n)]

for i in range(n):
    corr[i][i] = 1
print(np.array(corr))
print()

cholesky_decomp = cholesky(corr)
print(cholesky_decomp)
print()

print(np.matmul(cholesky_decomp, cholesky_decomp.T))

[[1.  0.4 0.4 0.4]
 [0.4 1.  0.4 0.4]
 [0.4 0.4 1.  0.4]
 [0.4 0.4 0.4 1. ]]

[[1.         0.         0.         0.        ]
 [0.4        0.91651514 0.         0.        ]
 [0.4        0.26186147 0.87831007 0.        ]
 [0.4        0.26186147 0.19518001 0.85634884]]

[[1.  0.4 0.4 0.4]
 [0.4 1.  0.4 0.4]
 [0.4 0.4 1.  0.4]
 [0.4 0.4 0.4 1. ]]


In [6]:
i,j = 4,1
lij = rho / np.sqrt((1 + (j-2) * rho) * (1 + j-1* rho))
ljj = np.sqrt((((1-rho) * (1 + (j-1) * rho))) / (1 + (j-2) * rho))
print(lij, ljj)

0.4082482904638631 1.0
